sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-23
    - android-28
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock 

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    - echo no | npm install -g grunt-cli
    - npm install
    - grunt compile

matrix:
  include:
    - stage: lint
      language: node_js
      os: linux
      node_js: "8"
      script: grunt lint

    - stage: build
      language: android
      os: linux
      env: 
        - Android="28"
      jdk: oraclejdk8
      before_install: nvm install 8.11.3
      script: "grunt ci:build:android"

    - stage: build
      os: osx
      env: 
        - iOS="10.3"
        - Xcode="8.3"
      osx_image: xcode8.3
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_install:
        - pip install --upgrade pip
        - pip install --user --upgrade matplotlib
        - pip install six
      script: "grunt ci:build:ios"

    - stage: webpack
      language: android
      os: linux
      env:
        - Android="28"
        - Platform="Android"
      jdk: oraclejdk8
      before_install: nvm install 8.11.3
      script: "grunt ci:webpack:android"
    
    - stage: webpack
      os: osx
      env: 
        - iOS="10.3"
        - Xcode="8.3"
        - Platform="iOS"
      osx_image: xcode8.3
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_install:
        - pip install --upgrade pip
        - pip install --user --upgrade matplotlib
        - pip install six
      script: "grunt ci:webpack:ios"

    - stage: deploy
      if: branch = release
      language: node_js 
      node_js: "8"
      before_deploy:
          - cd bin/dist
      deploy:
        provider: npm
        email: "peter@tangrasoft.com"
        api_key:
          secure: "C4Lon6juTC2yf5ca8Nu7cqqAPazDe7S/9iT0a+7NcTCBp5Q0b+G+CFzJuAiq4HQrIWiH3rBc1zVysxDtmupGQlEMwlIBQ6WdUDQ0UtG86ONGluEMLAQsZVryMWDeeKjRPktXbVfoNWaZciTc9JvRCJPcZq+UyOUNfPK2pduwUhKJi0IhCuIZd/mwxVyX9BAP2BspU556RKaBvHhkQ/X6cEMnztF11WiAZ3x1E4sjLTk30cKp7ckXxHgnG2jKPlVNUGTdtWBkhkgqtAF0sCOZ+Kq2f2mmDj8Ru9rE1ck6C9+wixMzdDrsol3F+6mRtpayzNDRQgecjqnJffRqoxvzb7A3cvE6WsQFR/EPt7gfN4Cipzy3t+vYpkDTrrjRlK5ZNsZiFtmaaRwOzr9ieisjkf8FBlr1ZMnsyUencfyg/PggxImEc90ti6LwU3r+cYzAMCDSbfnBvn2BwYXPf4usEGPuz+4ghtPbSyZn+a+Q/7c9KEwakMwYirQ0B7eoERuLOqfqEXViY6VAHKOLaVNHbocpgw0pGGjjnTUfeEWQvaqPukPQqzPuKSDWfV6JQ+QaLxiv84TTm82+JKADajEUO9GV/yUub1ZW9HQC4jyupftFNnjd8udoVu6BmHUwzCYUCzFzODg7gz2XzhRt+OMaIwrtuM28j8Eh+xUx+eeupY0="
        skip_cleanup: true
        on:
          branch: release
