sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-23
    - android-25
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock 

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    - echo no | npm install -g grunt-cli
    - npm install
    - grunt compile

matrix:
  include:
    - stage: lint
      language: node_js
      os: linux
      node_js: "6"
      script: grunt lint

    - stage: build
      language: android
      os: linux
      env: 
        - Android="26"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: "grunt ci:build:android"

    - stage: build
      os: osx
      env: 
        - iOS="10.3"
        - Xcode="8.3"
      osx_image: xcode8.3
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: "grunt ci:build:ios"

    - stage: webpack
      language: android
      os: linux
      env:
        - Android="26"
        - Platform="Android"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: "grunt ci:webpack:android"
    
    - stage: webpack
      os: osx
      env: 
        - iOS="10.3"
        - Xcode="8.3"
        - Platform="iOS"
      osx_image: xcode8.3
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: "grunt ci:webpack:ios"

    - stage: deploy
      if: branch = release
      language: node_js 
      node_js: "6"
      before_deploy:
          - cd bin/dist
      deploy:
        provider: npm
        email: "peter@tangrasoft.com"
        api_key:
            secure: "WP9az8lGUD8w8Mzm7N4kdy6Gg/eaV8e8Nc9ntKuGsp9k7Aar+n1XEWKw4xLoXjAXQyzFZLv6O1xqUtV3WYt7lzdlzxLRi6acQI0vK8fUR1s49f2yp8jhOKVXIy8vZajXNk4T1FEfRZOl6mD+0m+o177EqLb8lXlDxD/Y2tMvGEf8WAF4PIKYgFgdgW6rHYU3xU6anUid3WfXpj+E7WTPicoj7oXdzxawC6go5QG2T7dY/YN7Awj4Iaz4etwDQAg876tPYeT9CVA4Mh3NoDvGtxbBrvNwqsDEgSKWVdFVUmwj+maSWWMome7wWb1PcQgUiUjYsoVwdtDBa+lImnraNUCbTO7gaI91Y0WBnnaHU+hMXuFGw4+1tqAfH9lDaqzqGfYTuRHMMYUCbSq8LyNXax5oJh8Jkws+c+2YX6qK7fo67DJ0NuKyfszZF4QyCsnBwrEIUMy/xPIC/HItisb+nZdF7ERLz0UxM73+2yYADgt0pVxqJpZFUeR+pcSsZdKQYKAzh1aCUHl2uOHmoTpWGjtybLn8AN7OQqcbMx+kkdJTGHtVrg3EZNtcdEt56TKR8Cd4xREJwb//XsjOx0huk+FCNTD95kXcaNeT2Z82CIPckjdigCZuyL7hHwflgImJQeKGa4c2aIvpaS+kpc0/Jz7l+dAXgy8hSRwFjfrDZVM="
        skip_cleanup: true
        on:
          branch: release